#ifndef SETTINGS_H
#define SETTINGS_H

#define FRAMEBUFFER_WIDTH 960
#define FRAMEBUFFER_HEIGHT 600


#define PLAYER_SIZE_STARTING 150
#define PLAYER_MOVEMENT_SPEED 3
#define PLAYER_POS_X_STARTING_POSITION 400

#define PLAYER_Y_BASE_POSITION 380
#define PLAYER_JUMP_HEIGHT 800
#define GRAVITY 2000.0f
#define JUMP_VELOCITY 1200.0f

#define FAST_FALL_VELOCITY 0.0f

#define GROUND_LEVEL_Y 480

#define OBSTACLE_BASE_SIZE 250
#define OBSTACLE_Y_BASE_POSITION 300
#define OBSTACLE_COURSE_BASE_WIDTH 250.0f
#define OBSTACLE_COURSE_STARTING_X 900.0f
#define OBSTACLE_COURSE_MOVEMENT_SPEED 200.0f

#define BONUS_BASE_SIZE 70
#define BONUS_Y_BASE_POSITION 100
#define BONUS_COURSE_BASE_WIDTH 150.0f
#define BONUS_COURSE_STARTING_X 900.0f
#define BONUS_COURSE_MOVEMENT_SPEED 100.0f
#define BONUS_BASE_VALUE 200

#define MAX_SPEED_FACTOR 6.0f


#endif