#ifndef SETTINGS_H
#define SETTINGS_H

#define DRAW_TRANSPARENCY 1

#define FRAMEBUFFER_WIDTH 1920
#define FRAMEBUFFER_HEIGHT 1200

#define PLAYER_SIZE_STARTING 400
#define PLAYER_SIZE_MIN 390
#define PLAYER_SIZE_MAX 410

#define PLAYER_X_STARTING_POSITION 50
#define PLAYER_Y_GROUND_POSITION 880

#define GRAVITY 2000.0f
#define JUMP_VELOCITY 1400.0f
#define FAST_FALL_VELOCITY 0.0f

#define GROUND_LEVEL_Y 800

// obstacle settings
#define OBSTACLE_BASE_SIZE 180
#define OBSTACLE_Y_GROUND_POSITION 900
#define OBSTACLE_COURSE_BASE_WIDTH 500.0f
#define OBSTACLE_COURSE_STARTING_X 1920.0f
#define OBSTACLE_COURSE_MOVEMENT_SPEED 220.0f

#define MAX_GAME_SPEED_FACTOR 6.0f

// bonus token settings
#define BONUS_BASE_SIZE 150
#define BONUS_Y_BASE_POSITION 200
#define BONUS_COURSE_BASE_WIDTH 500.0f
#define BONUS_COURSE_STARTING_X 1940.0f
#define BONUS_COURSE_MOVEMENT_SPEED 220.0f
#define BONUS_BASE_VALUE 200

#endif